[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "2SWBn7wY6rYrXAk65YomV3VuAch5XgUh9qYVpsm9ai18"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
